# http://www.ruanyifeng.com/blog/2008/02/codes_for_language_names.html
language: "zh-Hans"

# site title
title: "Zhongyi I/O"

subtitle: "➩ Make something better for the world. ✌"

# Miscelaneous
favicon: "/favicon.ico"

# the truncate length of index"s post
truncate: 100

# Google Analytics
google_analytics_id: "UA-109699693-1"

# gitment
github_owner: "dzhongyi"
github_repo: "zhongyi.io"
github_client_id: "61c1e430371b91c5e33c"
github_client_secret: "9d397f2d259c2ea9f9ee5617181ad7ce71e12b6f"

# post author
author: "戴忠意"

# about
linkedin: dzhongyi